mathigayathri2001/U-break-WE-fix

README.md

Created use cases for the application

---

models/user.js

created user model

---

models/handyman.js

created handyman model

---

models/index.js
models/service.js

created service and index model

created service model and connected all models to index model

---

controllers/userController.js

Implemented user controller

---

controllers/handymanController.js

implemented handyman controller

---

routes/api/user.js

Implemented api user routes using controller functions

---

routes/api/handyman.js

Implemented api handyman routes using controller functions

---

routes/api/index.js

created index router for user and handyman api

---

routes/index.js

added all api routers in index and exporting as a router

all api routes added into index and exporting as a router

---

controllers/handymanController.js
controllers/userController.js
models/service.js
routes/api/handyman.js
routes/api/index.js
routes/api/user.js
routes/index.js
scripts/seedDB.js

bug fixes and added seeds to the database

---

client/src/App.js
client/src/pages/signUp.js

implemented signup page and connected to the react router

---

scripts/seedDB.js

created seeds for services

---

models/handyman.js
models/index.js
models/service.js

created service model

---

client/src/pages/login.js

implemented login page for user & handyman

implemented login page for user & handyman

---

client/src/App.js
client/src/pages/signUp.js

modified paths to login page and added routes to app.js

modified paths to login page

---

client/src/pages/handysignUp.js

created handyman signup page

---

client/src/App.js
client/src/utils/API.js
controllers/handymanController.js
models/handyman.js

creating post requests to the front end handyman and made some small changes

creating post requests to the front end handyman

---

client/src/components/Location/index.js
client/src/pages/handysignUp.js
package-lock.json
package.json

Google location component implemented

Google location component added to the signup page

---

controllers/userController.js
package-lock.json
package.json

packages added for authentication

Added required packages for the authentication

---

client/src/utils/auth-context.js
models/http-error.js

2) created authcontext to initialize login and signup variables required for further authorization functionalities

implemented 1) helper contexts in models for http error handling

---

client/src/App.js
client/src/pages/handysignUp.js
client/src/utils/API.js
client/src/utils/auth-context.js
controllers/handymanController.js
models/handyman.js
routes/api/handyman.js

Authentication handyman signup and login implementation.

Implemented jwt token based Authentication signup and login

---

scripts/seed.js

created seeds for service list

created seeds for service list

---

client/src/components/Location/index.js
client/src/pages/handysignUp.js

implemented location components

implemented location components

---

client/src/components/Searchbar/index.js
client/src/pages/handysignUp.js
models/handyman.js
models/service.js
scripts/seed.js

Modified seeds

---

client/src/App.js
client/src/pages/handysearch.js
client/src/pages/signUp.js
client/src/utils/API.js

implemented search by location functionality

implemented search by location functionality

---

client/src/components/Location/index.js
client/src/pages/handysearch.js
client/src/pages/handysignUp.js
client/src/utils/API.js
controllers/handymanController.js

changed location value to new input value

changed the location value

---

client/src/components/Card/index.js
client/src/components/HandyResult/index.js
client/src/components/HandyResult/style.css
client/src/components/List/index.js
client/src/components/List/style.css
client/src/components/Userlogin/index.js
client/src/pages/handysearch.js
client/src/utils/API.js

created card components

---

client/src/utils/API.js
client/src/utils/handy-context.js
controllers/serviceOrderController.js
models/index.js
models/serviceorder.js
routes/api/index.js
routes/api/serviceorder.js

created context globally  to store selected handyman

created context globally  to store selected handyman

---

client/src/App.js
client/src/pages/handysearch.js
client/src/pages/servicerequest.js
client/src/utils/auth-context.js
models/servicerequest.js
package-lock.json
package.json

2) save selected handymanid in context and use it in the service request submission processing

1) updated servicerequest model to store userid and handymanid

---

client/src/App.js
client/src/components/Logout/index.js
client/src/components/ViewRequest/index.js
client/src/pages/viewUserRequest.js
client/src/utils/API.js
controllers/handymanController.js
controllers/serviceRequestController.js
models/servicerequest.js
routes/api/handyman.js
routes/api/index.js
routes/api/servicerequest.js

ceated viewuserrequestpage for viewig the request

ceated viewuserrequestpage for viewig the request

---

client/src/pages/handysearch.js

implemented on click functionality to get the handyman

implemented on click functionality to get the handyman

---

client/src/components/HandyResult/index.js
client/src/components/ViewHandyRequest/index.js
client/src/pages/handysearch.js
client/src/pages/viewHandyRequest.js
client/src/utils/API.js
controllers/serviceRequestController.js
routes/api/servicerequest.js

created button for status functionality

created button for status functionality

---

client/src/components/Handylogin/index.js
client/src/components/ReqNav/index.js
client/src/components/ReqNav/style.css
client/src/components/Userlogin/index.js
client/src/pages/handysearch.js

Implemented navbars for diffrent pages

---

client/src/App.css
client/src/App.js
client/src/components/Card/index.js
client/src/components/Footer/footer.js
client/src/components/HandyResult/index.js
client/src/components/List/index.js
client/src/components/List/style.css
client/src/components/Navbar/index.js
client/src/components/ViewRequest/index.js
client/src/pages/handysearch.js
client/src/pages/viewHandyRequest.js
client/src/pages/viewUserRequest.js

implemented styles

---

client/src/components/Card/index.js
client/src/components/HandyResult/index.js
client/src/components/Location/index.js
client/src/components/Searchbar/index.js
client/src/components/ViewHandyRequest/index.js
client/src/components/ViewRequest/index.js
client/src/pages/handysearch.js
client/src/pages/servicerequest.js
client/src/pages/viewHandyRequest.js

added styles for the pages

---

client/src/components/BackNav/index.js
client/src/components/BackNav/style.css
client/src/components/ViewHandyRequest/index.js
client/src/components/ViewRequest/index.js
client/src/pages/viewHandyRequest.js
client/src/pages/viewUserRequest.js

updated refresh page to get data from local storage

updated refresh page to get data from local storage

---

client/public/index.html
client/src/App.css
client/src/App.js
client/src/components/Handylogin/index.js
client/src/components/Navbar/index.js
client/src/components/Userlogin/index.js
client/src/pages/handysignUp.js
client/src/pages/signUp.js

updated styles

---

client/src/App.js
client/src/components/Footer/index.js
client/src/components/Footer1/index.js
client/src/pages/handysearch.js
client/src/pages/handysignUp.js
client/src/pages/homepage.js
client/src/pages/login.js
client/src/pages/servicerequest.js
client/src/pages/signUp.js
client/src/pages/viewHandyRequest.js
client/src/pages/viewUserRequest.js
package-lock.json
package.json
scripts/seed.js
server.js

modified styles and switch routes

modified styles and switch routes

---

server.js

updated server with mongoosedb

updated server with mongoosedb

---

scripts/seed.js

updated db name in seed

---

scripts/seed.js
server.js

modified database name

---

package-lock.json
package.json

added dependencies in pacakage.json

added dependencies in pacakage.json

---

README.md
client/src/components/Navbar/index.js

ReadMe added for project
